id: waseem-2023-issues-causes-solutions
title: Understanding the Issues, Their Causes and Solutions in Microservices Systems
authors: Waseem, M. et al.
year: 2023
venue: Journal of Systems and Software
url: https://arxiv.org/pdf/2302.01894
retrieved: '2026-09-30'
type: peer_reviewed
status: V
verified: true
blueprints:
- misc
files:
- paper.pdf
