id: man-errno-3
title: errno(3)
url: https://man7.org/linux/man-pages/man3/errno.3.html
retrieved: '2026-09-30'
type: doc
status: M
verified: false
blueprints:
- fd-exhaustion
files:
- page.html
- page.md
- page_files/
