id: arzani-2016-netpoirot
title: Taking the Blame Game out of Data Centers Operations with NetPoirot
authors: Arzani, B.; Ciraci, S.; Loo, B. T.; Schuster, A.; Outhred, G.
year: 2016
venue: SIGCOMM 2016
doi: 10.1145/2934872.2934884
retrieved: '2026-09-30'
type: peer_reviewed
status: M
verified: false
blueprints:
- network-path-degradation
files:
- paper.pdf
