id: kernel-cfs-design-doc
title: CFS Scheduler design documentation
url: https://docs.kernel.org/scheduler/sched-design-CFS.html
retrieved: '2026-09-30'
type: doc
status: M
verified: false
blueprints:
- priority-inversion-nice
files:
- page.html
- page.md
- page_files/
